controller_manager:
  ros__parameters:
    update_rate: 30
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
