twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav_smoothed
        timeout: 0.5
        priority: 10
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 100
