<?xml version="1.0"?>
<package format="3">
  <name>action_demo_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 C++ action_demo nodes.</description>

  <maintainer email="anchuanxu@todo.todo">ROS Academy</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>action_demo_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
