<?xml version="1.0"?>
<package format="3">
  <name>name_demo_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 namespace and parameter demo.</description>

  <maintainer email="anchuanxu@todo.todo">ROS Academy</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
