<?xml version="1.0"?>
<package format="3">
  <name>topic_demo_py</name>
  <version>0.1.0</version>
  <description>ROS 2 Python topic_demo nodes.</description>

  <maintainer email="anchuanxu@todo.todo">ROS Academy</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>topic_demo_interfaces</depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
